version: '3'
services:
  admin:
    build: ./admin
    ports:
      - "3000:3000"
    volumes:
      - ./admin/src:/app/src
    depends_on:
      - mysql_db
    
  main:
    build: ./main
    ports:
      - "4000:4000"
    volumes:
      - ./main/src:/app/src
    
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser123
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    
  
